rtimv: circleTimeSeries Class Reference
circleTimeSeries Class Reference
#include <circleTimeSeries.hpp>
Public Member Functions
circleTimeSeries (size_t sz, bool useage)
void set_length (size_t l)
size_t get_length () const
virtual size_t size () const
void add_point (double nt, double ny)
size_t sample_i (size_t i) const
void clear ()
virtual double x (size_t i) const
virtual double y (size_t i) const
virtual QPointF sample (size_t i) const
virtual QRectF boundingRect () const
Public Attributes
std::vector< double > t
std::vector< double > Y
std::vector< double > age
int cursor
size_t _size
double minY
double maxY
bool useAge
Detailed Description
Definition at line 13 of file circleTimeSeries.hpp.
Constructor & Destructor Documentation
circleTimeSeries()
circleTimeSeries::circleTimeSeries (size_t sz, bool useage) inline
Definition at line 16 of file circleTimeSeries.hpp.
Member Function Documentation
add_point()
void circleTimeSeries::add_point (double nt, double ny) inline
Definition at line 50 of file circleTimeSeries.hpp.
boundingRect()
virtual QRectF circleTimeSeries::boundingRect () const inline virtual
Definition at line 156 of file circleTimeSeries.hpp.
clear()
void circleTimeSeries::clear () inline
Definition at line 123 of file circleTimeSeries.hpp.
get_length()
size_t circleTimeSeries::get_length () const inline
Definition at line 39 of file circleTimeSeries.hpp.
Referenced by add_point().
sample()
virtual QPointF circleTimeSeries::sample (size_t i) const inline virtual
Definition at line 147 of file circleTimeSeries.hpp.
sample_i()
size_t circleTimeSeries::sample_i (size_t i) const inline
Definition at line 116 of file circleTimeSeries.hpp.
Referenced by add_point(), boundingRect(), x(), and y().
set_length()
void circleTimeSeries::set_length (size_t l) inline
Definition at line 32 of file circleTimeSeries.hpp.
Referenced by circleTimeSeries().
size()
virtual size_t circleTimeSeries::size () const inline virtual
Definition at line 43 of file circleTimeSeries.hpp.
x()
virtual double circleTimeSeries::x (size_t i) const inline virtual
Definition at line 131 of file circleTimeSeries.hpp.
Referenced by sample().
y()
virtual double circleTimeSeries::y (size_t i) const inline virtual
Definition at line 142 of file circleTimeSeries.hpp.
Referenced by sample().
Member Data Documentation
_size
size_t circleTimeSeries::_size
Definition at line 42 of file circleTimeSeries.hpp.
Referenced by add_point(), circleTimeSeries(), sample_i(), and size().
age
std::vector<double> circleTimeSeries::age
Definition at line 30 of file circleTimeSeries.hpp.
cursor
int circleTimeSeries::cursor
Definition at line 41 of file circleTimeSeries.hpp.
Referenced by add_point(), and circleTimeSeries().
maxY
double circleTimeSeries::maxY
Definition at line 46 of file circleTimeSeries.hpp.
Referenced by circleTimeSeries().
minY
double circleTimeSeries::minY
Definition at line 45 of file circleTimeSeries.hpp.
Referenced by circleTimeSeries().
t
std::vector<double> circleTimeSeries::t
Definition at line 28 of file circleTimeSeries.hpp.
useAge
bool circleTimeSeries::useAge
Definition at line 48 of file circleTimeSeries.hpp.
Referenced by circleTimeSeries().
Y
std::vector<double> circleTimeSeries::Y
Definition at line 29 of file circleTimeSeries.hpp.
The documentation for this class was generated from the following file:
/home/jrmales/Source/c/rtimv/src/circleTimeSeries.hpp