rtimv: imviewerForm Class Reference
imviewerForm Class Reference
#include <imviewerform.hpp>
Public Member Functions
imviewerForm (const std::vector< std::string > &shkeys, QWidget *Parent=0, Qt::WindowFlags f=0)
virtual void onConnect ()
Called on initial connection to the image stream, sets matching aspect ratio.
virtual void postSetImsize ()
Changes the image size, but only if necessary.
void setTarget ()
Setup the target lines.
virtual void post_zoomLevel ()
virtual void postChangeImdata ()
to call after change imdata does its work.
virtual void updateFPS ()
Called whenever the displayed image updates its FPS.
virtual void updateAge ()
Called whenever the displayed image updates its Age.
virtual void keyPressEvent (QKeyEvent *)
void launchControlPanel ()
float get_act_xcen ()
float get_act_ycen ()
void setPointerOverZoom (float poz)
QGraphicsScene * get_qgs ()
void freezeRealTime ()
void reStretch ()
void change_center (bool movezoombox=true)
void set_viewcen (float x, float y, bool movezoombox=true)
float get_xcen ()
float get_ycen ()
void squareDown ()
Matches the viewport to the same aspect ratio as the image data, by decreasing the area.
void squareUp ()
Matches the viewport to the same aspect ratio as the image data, by increasing the area.
void launchImStats ()
int targetXc (float txc)
Set the x-coordinate of the target.
float targetXc ()
Get the x-coordinate of the target.
int targetYc (float tyc)
Set the y-coordinate of the target.
float targetYc ()
Get the y-coordinate of the target.
virtual void post_setUserBoxActive (bool usba)
int setAutoScale (bool as)
int toggleAutoScale ()
int center ()
int showFPSGage (bool sfg)
int toggleFPSGage ()
int toggleUserBox ()
int toggleStatsBox ()
int setDarkSub (bool ds)
int toggleDarkSub ()
int setApplyMask (bool am)
int toggleApplyMask ()
int setApplySatMask (bool as)
int toggleApplySatMask ()
int toggleLogLinear ()
int toggleTarget ()
Public Member Functions inherited from imviewer
imviewer (const std::vector< std::string > &shkeys, QWidget *Parent=0, Qt::WindowFlags f=0)
QPixmap * getPixmap ()
Get the QPixMap pointer.
void changeImdata (bool newdata=false)
Updates the QImage and basic statistics after a new image.
float get_imdat_min ()
float get_imdat_max ()
float zoomLevel ()
float zoomLevelMin ()
float zoomLevelMax ()
void zoomLevel (float zl)
void set_RealTimeEnabled (int)
void set_RealTimeStopped (int)
void setImsize (uint32_t x, uint32_t y)
uint32_t nx ()
Get the number of x pixels.
uint32_t ny ()
Get the number of y pixels.
void timeout (int to)
Set the image display timeout.
pixelF pixel ()
Returns a pointer to the static pixel value calculation function for the current calibration configuration.
void load_colorbar (int)
int get_current_colorbar ()
void set_colorbar_mode (int mode)
int get_colorbar_mode ()
void set_cbStretch (int)
int get_cbStretch ()
pixelIndexF pixelIndex ()
void mindat (float md)
float mindat ()
void maxdat (float md)
float maxdat ()
void bias (float b)
float bias ()
void bias_rel (float b)
float bias_rel ()
void contrast (float c)
float contrast ()
void contrast_rel (float cr)
float contrast_rel ()
int getUserBoxActive ()
void setUserBoxActive (bool usba)
Public Attributes
StretchBox * userBox
StretchBox * statsBox
StretchBox * guideBox
StretchCircle * userCircle
imviewerStats * imStats
Public Attributes inherited from imviewer
bool m_subtractDark {false}
bool m_applyMask {false}
bool m_applySatMask {false}
Protected Slots
void changeCenter ()
void resizeEvent (QResizeEvent *)
Calls changeCenter() so that the display stays centered when user resizes.
void changeMouseCoords ()
Receive signal that the viewport mouse coordinates have changed.
void viewLeftPressed (QPointF mp)
void viewLeftClicked (QPointF mp)
void viewRightPressed (QPointF mp)
void viewRightClicked (QPointF mp)
void onWheelMoved (int delta)
void doLaunchStatsBox ()
void doHideStatsBox ()
void imStatsClosed (int)
void statsBoxMoved (const QRectF &newr)
void statsBoxRejectMouse ()
void userBoxMoved (const QRectF &newr)
void userBoxRejectMouse ()
void guideBoxMoved (const QRectF &newr)
void guideBoxRejectMouse ()
void userCircleResized (const float &rad)
void userCircleMoved (const QRectF &newr)
void userCircleMouseIn ()
void userCircleMouseOut ()
void userCircleRejectMouse ()
Protected Slots inherited from imviewer
void timerout ()
Function called by m_timer expiration.
Protected Member Functions
void mouseMoveEvent (QMouseEvent *e)
void nullMouseCoords ()
void updateMouseCoords ()
Update the GUI for a change in mouse coordinates in the viewport.
Protected Member Functions inherited from imviewer
int calcPixIndex (float d)
Calculates the color map index of a value.
Protected Attributes
imviewerControlPanel * imcp
float pointerOverZoom
QGraphicsScene * qgs
QGraphicsPixmapItem * qpmi
QGraphicsLineItem * nup
QGraphicsLineItem * nup_tip
float ScreenZoom
bool rightClickDragging
QPointF rightClickStart
float biasStart
float contrastStart
bool NullMouseCoords
float m_targetXc {0.5}
The x-coordinate of the target, 0<= x <= 1.
float m_targetYc {0.5}
The y-coordinate of the target, 0<= y <= 1.
bool m_targetVisible
Flag controlling whether the target is visible.
QGraphicsLineItem * m_cenLineVert
The vertical line component of the target.
QGraphicsLineItem * m_cenLineHorz
The horizontal line component of the target.
bool m_showLoopStat {false}
bool m_showSaveStat {false}
bool m_showFPSGage {true}
Protected Attributes inherited from imviewer
QImage * m_qim {nullptr}
A QT image, used to store the color-map encoded data.
QPixmap m_qpm
A QT pixmap, used to prep the QImage for display.
bool amChangingimdata
float sat_level {1e30}
int saturated {0}
float imdat_min
float imdat_max
float m_zoomLevel {1}
float m_zoomLevelMin {0.125}
float m_zoomLevelMax {64}
bool RealTimeEnabled {true}
Controls whether imviewer is using real-time data.
bool RealTimeStopped {false}
Set when user temporarily freezes real-time data viewing.
float * m_lowPassFiltered {nullptr}
bool m_applyLPFilter
int m_lpFilterType
uint32_t m_nx {0}
The number of pixels in the x (horizontal) direction.
uint32_t m_ny {0}
The number of pixels in the y (vertical) direction.
std::vector< rtimvImage * > m_images
QTimer m_timer
When this times out imviewer checks for a new image.
int m_timeout {100}
The timeout for checking for a new images, ms.
int m_mincol {0}
The minimum index to use for the color table.
int m_maxcol {253}
The maximum index to use for the color table.
int m_maskcol {254}
The index in the color table to use for the mask color.
int m_satcol {255}
The index in the color table to use for the saturation color.
int colorbar_mode {minmaxglobal}
int m_cbStretch {stretchLinear}
int current_colorbar {colorbarBone}
QColor warning_color
float m_mindat
The minimum data value used for scaling.
float m_maxdat
The maximum data valuse used for scaling.
bool m_autoScale {false}
int userBoxActive {0}
int64_t userBox_i0
int64_t userBox_i1
int64_t userBox_j0
int64_t userBox_j1
int64_t guideBox_i0
int64_t guideBox_i1
int64_t guideBox_j0
int64_t guideBox_j1
float userBox_max
float userBox_min
Private Attributes
Ui::imviewerForm ui
Additional Inherited Members
Public Types inherited from imviewer
typedef float(* pixelF) (imviewer *, size_t)
The fuction pointer type for accessing pixels with calibrations applied.
enum en_cbStretches {
stretchLinear, stretchLog, stretchPow, stretchSqrt,
stretchSquare, cbStretches_max
}
enum colorbars {
colorbarGrey, colorbarJet, colorbarHot, colorbarBone,
colorbarRed, colorbarGreen, colorbarBlue, colorbarMax
}
enum colorbar_modes {
minmaxglobal, minmaxview, minmaxbox, user,
colorbar_modes_max
}
typedef int(* pixelIndexF) (float)
Public Slots inherited from imviewer
void handleSigSegv ()
Static Public Member Functions inherited from imviewer
static void st_handleSigSegv (int signum, siginfo_t *siginf, void *ucont)
static float pixel_noCal (imviewer *imv, size_t idx)
Access pixels with no calibrations applied.
static float pixel_subDark (imviewer *imv, size_t idx)
Access pixels with dark subtraction applied.
static float pixel_applyMask (imviewer *imv, size_t idx)
Access pixels with the mask applied.
static float pixel_subDarkApplyMask (imviewer *imv, size_t idx)
Access pixels with dark subtraction and masking applied.
static int pixelIndex_linear (float d)
static int pixelIndex_log (float d)
static int pixelIndex_pow (float d)
static int pixelIndex_sqrt (float d)
static int pixelIndex_square (float d)
Detailed Description
Definition at line 36 of file imviewerform.hpp.
Constructor & Destructor Documentation
imviewerForm()
imviewerForm::imviewerForm (const std::vector< std::string > & shkeys, QWidget * Parent = 0, Qt::WindowFlags f = 0)
Definition at line 3 of file imviewerform.cpp.
Member Function Documentation
center()
int imviewerForm::center ()
Definition at line 982 of file imviewerform.cpp.
Referenced by keyPressEvent().
change_center()
void imviewerForm::change_center (bool movezoombox = true)
Definition at line 350 of file imviewerform.cpp.
Referenced by changeCenter(), get_qgs(), post_zoomLevel(), resizeEvent(), and set_viewcen().
changeCenter
void imviewerForm::changeCenter () protected slot
Definition at line 421 of file imviewerform.cpp.
Referenced by get_ycen().
changeMouseCoords
void imviewerForm::changeMouseCoords () protected slot
Receive signal that the viewport mouse coordinates have changed.
Definition at line 520 of file imviewerform.cpp.
doHideStatsBox
void imviewerForm::doHideStatsBox () protected slot
Definition at line 679 of file imviewerform.cpp.
Referenced by launchControlPanel(), and toggleStatsBox().
doLaunchStatsBox
void imviewerForm::doLaunchStatsBox () protected slot
Definition at line 656 of file imviewerform.cpp.
Referenced by launchControlPanel(), and toggleStatsBox().
freezeRealTime()
void imviewerForm::freezeRealTime ()
Definition at line 305 of file imviewerform.cpp.
Referenced by get_qgs(), and keyPressEvent().
get_act_xcen()
float imviewerForm::get_act_xcen ()
get_act_ycen()
float imviewerForm::get_act_ycen ()
get_qgs()
QGraphicsScene* imviewerForm::get_qgs () inline
Definition at line 91 of file imviewerform.hpp.
Referenced by imviewerControlPanel::set_PointerViewMode(), imviewerControlPanel::updateMouseCoords(), and imviewerControlPanel::viewLeftPressed().
get_xcen()
float imviewerForm::get_xcen () inline
Definition at line 103 of file imviewerform.hpp.
Referenced by imviewerControlPanel::on_view_dl_clicked(), imviewerControlPanel::on_view_down_clicked(), imviewerControlPanel::on_view_dr_clicked(), imviewerControlPanel::on_view_left_clicked(), imviewerControlPanel::on_view_right_clicked(), imviewerControlPanel::on_view_ul_clicked(), imviewerControlPanel::on_view_up_clicked(), imviewerControlPanel::on_view_ur_clicked(), imviewerControlPanel::on_ycenEntry_editingFinished(), and imviewerControlPanel::set_ViewViewMode().
get_ycen()
float imviewerForm::get_ycen () inline
Definition at line 104 of file imviewerform.hpp.
Referenced by imviewerControlPanel::on_view_dl_clicked(), imviewerControlPanel::on_view_down_clicked(), imviewerControlPanel::on_view_dr_clicked(), imviewerControlPanel::on_view_left_clicked(), imviewerControlPanel::on_view_right_clicked(), imviewerControlPanel::on_view_ul_clicked(), imviewerControlPanel::on_view_up_clicked(), imviewerControlPanel::on_view_ur_clicked(), imviewerControlPanel::on_xcenEntry_editingFinished(), and imviewerControlPanel::set_ViewViewMode().
guideBoxMoved
void imviewerForm::guideBoxMoved (const QRectF & newr) protected slot
Definition at line 759 of file imviewerform.cpp.
Referenced by imviewerForm().
guideBoxRejectMouse
void imviewerForm::guideBoxRejectMouse () protected slot
Definition at line 775 of file imviewerform.cpp.
Referenced by imviewerForm().
imStatsClosed
void imviewerForm::imStatsClosed (int result) protected slot
Definition at line 694 of file imviewerform.cpp.
keyPressEvent()
void imviewerForm::keyPressEvent (QKeyEvent * ke) virtual
Definition at line 831 of file imviewerform.cpp.
launchControlPanel()
void imviewerForm::launchControlPanel ()
Definition at line 284 of file imviewerform.cpp.
Referenced by keyPressEvent().
launchImStats()
void imviewerForm::launchImStats ()
mouseMoveEvent()
void imviewerForm::mouseMoveEvent (QMouseEvent * e) protected
Definition at line 435 of file imviewerform.cpp.
nullMouseCoords()
void imviewerForm::nullMouseCoords () protected
Definition at line 441 of file imviewerform.cpp.
Referenced by mouseMoveEvent(), and updateMouseCoords().
onConnect()
void imviewerForm::onConnect () virtual
Called on initial connection to the image stream, sets matching aspect ratio.
Reimplemented from imviewer.
Definition at line 115 of file imviewerform.cpp.
onWheelMoved
void imviewerForm::onWheelMoved (int delta) protected slot
Definition at line 558 of file imviewerform.cpp.
post_setUserBoxActive()
void imviewerForm::post_setUserBoxActive (bool usba) virtual
Definition at line 825 of file imviewerform.cpp.
post_zoomLevel()
void imviewerForm::post_zoomLevel () virtual
Reimplemented from imviewer.
Definition at line 191 of file imviewerform.cpp.
Referenced by center(), postChangeImdata(), postSetImsize(), resizeEvent(), and setPointerOverZoom().
postChangeImdata()
void imviewerForm::postChangeImdata () virtual
to call after change imdata does its work.
Reimplemented from imviewer.
Definition at line 231 of file imviewerform.cpp.
postSetImsize()
void imviewerForm::postSetImsize () virtual
Changes the image size, but only if necessary.
to call after set_imsize to handle allocations for derived classes
Reimplemented from imviewer.
Definition at line 120 of file imviewerform.cpp.
resizeEvent
void imviewerForm::resizeEvent (QResizeEvent *) protected slot
Calls changeCenter() so that the display stays centered when user resizes.
Definition at line 426 of file imviewerform.cpp.
Referenced by get_ycen().
reStretch()
void imviewerForm::reStretch ()
Definition at line 318 of file imviewerform.cpp.
Referenced by get_qgs(), and keyPressEvent().
set_viewcen()
void imviewerForm::set_viewcen (float x, float y, bool movezoombox = true)
Definition at line 376 of file imviewerform.cpp.
Referenced by center(), get_qgs(), imviewerControlPanel::on_view_center_clicked(), imviewerControlPanel::on_view_dl_clicked(), imviewerControlPanel::on_view_down_clicked(), imviewerControlPanel::on_view_dr_clicked(), imviewerControlPanel::on_view_left_clicked(), imviewerControlPanel::on_view_right_clicked(), imviewerControlPanel::on_view_ul_clicked(), imviewerControlPanel::on_view_up_clicked(), imviewerControlPanel::on_view_ur_clicked(), imviewerControlPanel::on_xcenEntry_editingFinished(), imviewerControlPanel::on_ycenEntry_editingFinished(), postChangeImdata(), postSetImsize(), and imviewerControlPanel::viewBoxMoved().
setApplyMask()
int imviewerForm::setApplyMask (bool am)
Definition at line 1104 of file imviewerform.cpp.
Referenced by toggleApplyMask().
setApplySatMask()
int imviewerForm::setApplySatMask (bool as)
Definition at line 1131 of file imviewerform.cpp.
Referenced by toggleApplySatMask().
setAutoScale()
int imviewerForm::setAutoScale (bool as)
Definition at line 955 of file imviewerform.cpp.
Referenced by main(), and toggleAutoScale().
setDarkSub()
int imviewerForm::setDarkSub (bool ds)
Definition at line 1077 of file imviewerform.cpp.
Referenced by toggleDarkSub().
setPointerOverZoom()
void imviewerForm::setPointerOverZoom (float poz)
Definition at line 342 of file imviewerform.cpp.
Referenced by imviewerControlPanel::on_overZoom1_clicked(), imviewerControlPanel::on_overZoom2_clicked(), and imviewerControlPanel::on_overZoom4_clicked().
setTarget()
void imviewerForm::setTarget ()
Setup the target lines.
Definition at line 167 of file imviewerform.cpp.
Referenced by postSetImsize(), targetXc(), and targetYc().
showFPSGage()
int imviewerForm::showFPSGage (bool sfg)
Definition at line 1049 of file imviewerform.cpp.
Referenced by main(), and toggleFPSGage().
squareDown()
void imviewerForm::squareDown ()
Matches the viewport to the same aspect ratio as the image data, by decreasing the area.
Maintains the smaller of width and height, decreasing the other to match the aspect of the image.
Invoked by the "[" key.
squareUp()
Todo:
make threshold responsive to current dimensions so we don't enter loops.
Definition at line 385 of file imviewerform.cpp.
Referenced by get_ycen(), keyPressEvent(), and onConnect().
squareUp()
void imviewerForm::squareUp ()
Matches the viewport to the same aspect ratio as the image data, by increasing the area.
Maintains the larger of width and height, increasing the other to match the aspect of the image.
Invoked by the "]" key.
squareDown()
Todo:
make threshold responsive to current dimensions so we don't enter loops.
Definition at line 403 of file imviewerform.cpp.
Referenced by get_ycen(), and keyPressEvent().
statsBoxMoved
void imviewerForm::statsBoxMoved (const QRectF & newr) protected slot
Definition at line 711 of file imviewerform.cpp.
Referenced by imviewerForm().
statsBoxRejectMouse
void imviewerForm::statsBoxRejectMouse () protected slot
Definition at line 726 of file imviewerform.cpp.
Referenced by imviewerForm().
targetXc() [1/2]
int imviewerForm::targetXc (float txc)
Set the x-coordinate of the target.
The coordinate is set as a fraction of the image, 0 <= targetXc <= 1.0 It will be clamped to this range by this function..
Returns
0 on success
Parameters
[in] txc the new target x coordinate
Definition at line 621 of file imviewerform.cpp.
Referenced by main().
targetXc() [2/2]
float imviewerForm::targetXc ()
Get the x-coordinate of the target.
Returns
the current value of m_targetXc
Definition at line 633 of file imviewerform.cpp.
targetYc() [1/2]
int imviewerForm::targetYc (float tyc)
Set the y-coordinate of the target.
The coordinate is set as a fraction of the image, 0 <= targetYc <= 1.0 It will be clamped to this range by this function..
Returns
0 on success
Parameters
[in] tyc the new target y coordinate
Definition at line 638 of file imviewerform.cpp.
Referenced by main().
targetYc() [2/2]
float imviewerForm::targetYc ()
Get the y-coordinate of the target.
Returns
the current value of m_targetYc
Definition at line 650 of file imviewerform.cpp.
toggleApplyMask()
int imviewerForm::toggleApplyMask ()
Definition at line 1119 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleApplySatMask()
int imviewerForm::toggleApplySatMask ()
Definition at line 1148 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleAutoScale()
int imviewerForm::toggleAutoScale ()
Definition at line 970 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleDarkSub()
int imviewerForm::toggleDarkSub ()
Definition at line 1092 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleFPSGage()
int imviewerForm::toggleFPSGage ()
Definition at line 1065 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleLogLinear()
int imviewerForm::toggleLogLinear ()
Definition at line 1160 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleStatsBox()
int imviewerForm::toggleStatsBox ()
Definition at line 1023 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleTarget()
int imviewerForm::toggleTarget ()
Definition at line 1178 of file imviewerform.cpp.
Referenced by keyPressEvent().
toggleUserBox()
int imviewerForm::toggleUserBox ()
Definition at line 992 of file imviewerform.cpp.
Referenced by keyPressEvent().
updateAge()
void imviewerForm::updateAge () virtual
Called whenever the displayed image updates its Age.
Reimplemented from imviewer.
Definition at line 574 of file imviewerform.cpp.
Referenced by updateFPS().
updateFPS()
void imviewerForm::updateFPS () virtual
Called whenever the displayed image updates its FPS.
Reimplemented from imviewer.
Definition at line 569 of file imviewerform.cpp.
updateMouseCoords()
void imviewerForm::updateMouseCoords () protected
Update the GUI for a change in mouse coordinates in the viewport.
Performs the following functions:
Decides whether or not the mouse is currently in the pixmap.
If it is not in the pixmap, clears the mouse coord text boxes
If it is, updates the moust coord text boxes
If the moust is right-clicked and dragging, updates the strech bias and contrast.
Definition at line 458 of file imviewerform.cpp.
Referenced by changeMouseCoords(), and postChangeImdata().
userBoxMoved
void imviewerForm::userBoxMoved (const QRectF & newr) protected slot
Definition at line 733 of file imviewerform.cpp.
Referenced by imviewerForm().
userBoxRejectMouse
void imviewerForm::userBoxRejectMouse () protected slot
Definition at line 749 of file imviewerform.cpp.
Referenced by imviewerForm().
userCircleMouseIn
void imviewerForm::userCircleMouseIn () protected slot
Definition at line 805 of file imviewerform.cpp.
Referenced by imviewerForm().
userCircleMouseOut
void imviewerForm::userCircleMouseOut () protected slot
Definition at line 810 of file imviewerform.cpp.
Referenced by imviewerForm().
userCircleMoved
void imviewerForm::userCircleMoved (const QRectF & newr) protected slot
Definition at line 793 of file imviewerform.cpp.
Referenced by imviewerForm().
userCircleRejectMouse
void imviewerForm::userCircleRejectMouse () protected slot
Definition at line 815 of file imviewerform.cpp.
Referenced by imviewerForm().
userCircleResized
void imviewerForm::userCircleResized (const float & rad) protected slot
Definition at line 783 of file imviewerform.cpp.
Referenced by imviewerForm().
viewLeftClicked
void imviewerForm::viewLeftClicked (QPointF mp) protected slot
Definition at line 534 of file imviewerform.cpp.
viewLeftPressed
void imviewerForm::viewLeftPressed (QPointF mp) protected slot
Definition at line 526 of file imviewerform.cpp.
viewRightClicked
void imviewerForm::viewRightClicked (QPointF mp) protected slot
Definition at line 552 of file imviewerform.cpp.
viewRightPressed
void imviewerForm::viewRightPressed (QPointF mp) protected slot
Definition at line 542 of file imviewerform.cpp.
Member Data Documentation
biasStart
float imviewerForm::biasStart protected
Definition at line 134 of file imviewerform.hpp.
Referenced by updateMouseCoords(), and viewRightPressed().
contrastStart
float imviewerForm::contrastStart protected
Definition at line 135 of file imviewerform.hpp.
Referenced by updateMouseCoords(), and viewRightPressed().
guideBox
StretchBox* imviewerForm::guideBox
Definition at line 169 of file imviewerform.hpp.
Referenced by guideBoxMoved(), guideBoxRejectMouse(), imviewerForm(), keyPressEvent(), postChangeImdata(), postSetImsize(), statsBoxRejectMouse(), userBoxRejectMouse(), and userCircleRejectMouse().
imcp
imviewerControlPanel* imviewerForm::imcp protected
Definition at line 65 of file imviewerform.hpp.
Referenced by change_center(), imviewerForm(), launchControlPanel(), nullMouseCoords(), post_zoomLevel(), postChangeImdata(), postSetImsize(), toggleStatsBox(), toggleUserBox(), updateMouseCoords(), viewLeftClicked(), and viewLeftPressed().
imStats
imviewerStats* imviewerForm::imStats
Definition at line 173 of file imviewerform.hpp.
Referenced by imviewerForm(), and postChangeImdata().
m_cenLineHorz
QGraphicsLineItem* imviewerForm::m_cenLineHorz protected
The horizontal line component of the target.
Definition at line 184 of file imviewerform.hpp.
Referenced by imviewerForm(), setTarget(), and toggleTarget().
m_cenLineVert
QGraphicsLineItem* imviewerForm::m_cenLineVert protected
The vertical line component of the target.
Definition at line 183 of file imviewerform.hpp.
Referenced by imviewerForm(), setTarget(), and toggleTarget().
m_showFPSGage
bool imviewerForm::m_showFPSGage {true} protected
Definition at line 244 of file imviewerform.hpp.
Referenced by freezeRealTime(), showFPSGage(), toggleFPSGage(), and updateAge().
m_showLoopStat
bool imviewerForm::m_showLoopStat {false} protected
Definition at line 242 of file imviewerform.hpp.
Referenced by updateAge().
m_showSaveStat
bool imviewerForm::m_showSaveStat {false} protected
Definition at line 243 of file imviewerform.hpp.
m_targetVisible
bool imviewerForm::m_targetVisible protected
Flag controlling whether the target is visible.
Definition at line 181 of file imviewerform.hpp.
Referenced by imviewerForm(), setTarget(), and toggleTarget().
m_targetXc
float imviewerForm::m_targetXc {0.5} protected
The x-coordinate of the target, 0<= x <= 1.
Definition at line 178 of file imviewerform.hpp.
Referenced by setTarget(), and targetXc().
m_targetYc
float imviewerForm::m_targetYc {0.5} protected
The y-coordinate of the target, 0<= y <= 1.
Definition at line 179 of file imviewerform.hpp.
Referenced by setTarget(), and targetYc().
NullMouseCoords
bool imviewerForm::NullMouseCoords protected
Definition at line 139 of file imviewerform.hpp.
Referenced by changeMouseCoords(), imviewerForm(), nullMouseCoords(), and updateMouseCoords().
nup
QGraphicsLineItem* imviewerForm::nup protected
Definition at line 86 of file imviewerform.hpp.
Referenced by imviewerForm(), keyPressEvent(), and post_zoomLevel().
nup_tip
QGraphicsLineItem* imviewerForm::nup_tip protected
Definition at line 87 of file imviewerform.hpp.
Referenced by imviewerForm(), keyPressEvent(), and post_zoomLevel().
pointerOverZoom
float imviewerForm::pointerOverZoom protected
Definition at line 67 of file imviewerform.hpp.
Referenced by imviewerForm(), post_zoomLevel(), and setPointerOverZoom().
qgs
QGraphicsScene* imviewerForm::qgs protected
Definition at line 83 of file imviewerform.hpp.
Referenced by get_qgs(), imviewerForm(), postChangeImdata(), and setTarget().
qpmi
QGraphicsPixmapItem* imviewerForm::qpmi protected
Definition at line 84 of file imviewerform.hpp.
Referenced by guideBoxMoved(), imviewerForm(), postChangeImdata(), set_viewcen(), updateMouseCoords(), userBoxMoved(), and userCircleMoved().
rightClickDragging
bool imviewerForm::rightClickDragging protected
Definition at line 132 of file imviewerform.hpp.
Referenced by imviewerForm(), updateMouseCoords(), viewRightClicked(), and viewRightPressed().
rightClickStart
QPointF imviewerForm::rightClickStart protected
Definition at line 133 of file imviewerform.hpp.
Referenced by updateMouseCoords(), and viewRightPressed().
ScreenZoom
float imviewerForm::ScreenZoom protected
Definition at line 89 of file imviewerform.hpp.
Referenced by post_zoomLevel(), postSetImsize(), resizeEvent(), and userCircleMoved().
statsBox
StretchBox* imviewerForm::statsBox
Definition at line 167 of file imviewerform.hpp.
Referenced by guideBoxRejectMouse(), imviewerForm(), postChangeImdata(), postSetImsize(), statsBoxRejectMouse(), toggleStatsBox(), userBoxRejectMouse(), and userCircleRejectMouse().
ui
Ui::imviewerForm imviewerForm::ui private
Definition at line 280 of file imviewerform.hpp.
Referenced by center(), change_center(), freezeRealTime(), get_xcen(), get_ycen(), imviewerForm(), nullMouseCoords(), post_zoomLevel(), postChangeImdata(), postSetImsize(), resizeEvent(), set_viewcen(), setApplyMask(), setApplySatMask(), setAutoScale(), setDarkSub(), showFPSGage(), toggleLogLinear(), toggleStatsBox(), toggleTarget(), toggleUserBox(), updateAge(), updateMouseCoords(), userCircleMouseIn(), userCircleMouseOut(), userCircleMoved(), and userCircleResized().
userBox
StretchBox* imviewerForm::userBox
Definition at line 165 of file imviewerform.hpp.
Referenced by guideBoxRejectMouse(), imviewerForm(), imviewerControlPanel::on_scaleModeCombo_activated(), post_setUserBoxActive(), postChangeImdata(), postSetImsize(), statsBoxRejectMouse(), toggleUserBox(), userBoxMoved(), userBoxRejectMouse(), and userCircleRejectMouse().
userCircle
StretchCircle* imviewerForm::userCircle
Definition at line 171 of file imviewerform.hpp.
Referenced by guideBoxRejectMouse(), imviewerForm(), keyPressEvent(), postSetImsize(), statsBoxRejectMouse(), userBoxRejectMouse(), userCircleMoved(), and userCircleRejectMouse().
The documentation for this class was generated from the following files:
/home/jrmales/Source/c/rtimv/src/imviewerform.hpp
/home/jrmales/Source/c/rtimv/src/imviewerform.cpp