rtimv: imviewerControlPanel Class Reference
imviewerControlPanel Class Reference
#include <imviewerControlPanel.h>
Public Slots
void set_PointerViewMode (int)
void on_pointerViewModecomboBox_activated (int)
void on_pointerSetLocButton_clicked ()
void set_pointerViewCen (QPointF mp)
void viewBoxMoved (const QRectF &newcen)
void on_scaleModeCombo_activated (int index)
void on_mindatSlider_valueChanged (int value)
void on_mindatEntry_editingFinished ()
void on_maxdatSlider_valueChanged (int value)
void on_maxdatEntry_editingFinished ()
void on_biasSlider_valueChanged (int value)
void on_biasEntry_editingFinished ()
void on_contrastSlider_valueChanged (int value)
void on_contrastEntry_editingFinished ()
void on_imtimerspinBox_valueChanged (int)
void on_statsBoxButton_clicked ()
Signals
void launchStatsBox ()
void hideStatsBox ()
Public Member Functions
imviewerControlPanel (imviewerForm *imv, Qt::WindowFlags f=0)
void update_panel ()
void update_ZoomSlider ()
void update_ZoomEntry ()
void set_ViewViewMode (int)
void update_xycenEntry ()
void update_whEntry ()
void updateMouseCoords (double x, double y, double v)
void nullMouseCoords ()
void viewLeftPressed (QPointF mp)
void viewLeftClicked (QPointF mp)
Public Attributes
QGraphicsScene * qgs_view
QGraphicsScene * qgs_empty
QGraphicsPixmapItem * qpmi_view
QGraphicsLineItem * viewLineVert
QGraphicsLineItem * viewLineHorz
StretchBox * viewBox
int ViewViewMode
QPointF pointerViewCen
int PointerViewMode
bool statsBoxButtonState
Ui::imviewerControlPanel ui
Protected Slots
void on_ZoomSlider_valueChanged (int value)
void on_Zoom1_clicked ()
void on_Zoom2_clicked ()
void on_Zoom4_clicked ()
void on_Zoom8_clicked ()
void on_Zoom16_clicked ()
void on_ZoomEntry_editingFinished ()
void on_overZoom1_clicked ()
void on_overZoom2_clicked ()
void on_overZoom4_clicked ()
void on_ViewViewModecheckBox_stateChanged (int)
void enableViewViewMode (int)
void on_xcenEntry_editingFinished ()
void on_ycenEntry_editingFinished ()
void on_widthEntry_editingFinished ()
void on_heightEntry_editingFinished ()
void on_view_center_clicked ()
void on_view_ul_clicked ()
void on_view_up_clicked ()
void on_view_ur_clicked ()
void on_view_right_clicked ()
void on_view_dr_clicked ()
void on_view_down_clicked ()
void on_view_dl_clicked ()
void on_view_left_clicked ()
void on_scaleTypeCombo_activated (int)
void on_colorbarCombo_activated (int)
Protected Member Functions
void setupMode ()
void setupCombos ()
void init_panel ()
void update_mindatSlider ()
void update_mindatEntry ()
void update_mindatRelEntry ()
void update_maxdatSlider ()
void update_maxdatEntry ()
void update_maxdatRelEntry ()
void update_biasSlider ()
void update_biasEntry ()
void update_biasRelEntry ()
void update_contrastSlider ()
void update_contrastEntry ()
void update_contrastRelEntry ()
Protected Attributes
imviewerForm * imv
bool IgnoreZoomSliderChange
bool PointerViewEmpty
bool PointerViewFixed
bool PointerViewWaiting
bool IgnoremindatSliderChange
bool IgnoremaxdatSliderChange
bool IgnorebiasSliderChange
bool IgnorecontrastSliderChange
Detailed Description
Definition at line 12 of file imviewerControlPanel.h.
Constructor & Destructor Documentation
imviewerControlPanel()
imviewerControlPanel::imviewerControlPanel (imviewerForm * imv, Qt::WindowFlags f = 0)
Definition at line 3 of file imviewerControlPanel.cpp.
Member Function Documentation
enableViewViewMode
void imviewerControlPanel::enableViewViewMode (int state) protected slot
Definition at line 333 of file imviewerControlPanel.cpp.
Referenced by on_ViewViewModecheckBox_stateChanged().
hideStatsBox
void imviewerControlPanel::hideStatsBox () signal
Referenced by on_statsBoxButton_clicked().
init_panel()
void imviewerControlPanel::init_panel () protected
Definition at line 91 of file imviewerControlPanel.cpp.
Referenced by imviewerControlPanel().
launchStatsBox
void imviewerControlPanel::launchStatsBox () signal
Referenced by on_statsBoxButton_clicked().
nullMouseCoords()
void imviewerControlPanel::nullMouseCoords ()
Definition at line 434 of file imviewerControlPanel.cpp.
Referenced by imviewerForm::nullMouseCoords().
on_biasEntry_editingFinished
void imviewerControlPanel::on_biasEntry_editingFinished () slot
Definition at line 788 of file imviewerControlPanel.cpp.
on_biasSlider_valueChanged
void imviewerControlPanel::on_biasSlider_valueChanged (int value) slot
Definition at line 770 of file imviewerControlPanel.cpp.
on_colorbarCombo_activated
void imviewerControlPanel::on_colorbarCombo_activated (int cb) protected slot
Definition at line 532 of file imviewerControlPanel.cpp.
on_contrastEntry_editingFinished
void imviewerControlPanel::on_contrastEntry_editingFinished () slot
Definition at line 823 of file imviewerControlPanel.cpp.
on_contrastSlider_valueChanged
void imviewerControlPanel::on_contrastSlider_valueChanged (int value) slot
Definition at line 803 of file imviewerControlPanel.cpp.
on_heightEntry_editingFinished
void imviewerControlPanel::on_heightEntry_editingFinished () protected slot
Definition at line 357 of file imviewerControlPanel.cpp.
on_imtimerspinBox_valueChanged
void imviewerControlPanel::on_imtimerspinBox_valueChanged (int to) slot
Definition at line 838 of file imviewerControlPanel.cpp.
on_maxdatEntry_editingFinished
void imviewerControlPanel::on_maxdatEntry_editingFinished () slot
Definition at line 757 of file imviewerControlPanel.cpp.
on_maxdatSlider_valueChanged
void imviewerControlPanel::on_maxdatSlider_valueChanged (int value) slot
Definition at line 739 of file imviewerControlPanel.cpp.
on_mindatEntry_editingFinished
void imviewerControlPanel::on_mindatEntry_editingFinished () slot
Definition at line 724 of file imviewerControlPanel.cpp.
on_mindatSlider_valueChanged
void imviewerControlPanel::on_mindatSlider_valueChanged (int value) slot
Definition at line 707 of file imviewerControlPanel.cpp.
on_overZoom1_clicked
void imviewerControlPanel::on_overZoom1_clicked () protected slot
Definition at line 257 of file imviewerControlPanel.cpp.
on_overZoom2_clicked
void imviewerControlPanel::on_overZoom2_clicked () protected slot
Definition at line 263 of file imviewerControlPanel.cpp.
on_overZoom4_clicked
void imviewerControlPanel::on_overZoom4_clicked () protected slot
Definition at line 268 of file imviewerControlPanel.cpp.
on_pointerSetLocButton_clicked
void imviewerControlPanel::on_pointerSetLocButton_clicked () slot
Definition at line 501 of file imviewerControlPanel.cpp.
on_pointerViewModecomboBox_activated
void imviewerControlPanel::on_pointerViewModecomboBox_activated (int pvm) slot
Definition at line 496 of file imviewerControlPanel.cpp.
on_scaleModeCombo_activated
void imviewerControlPanel::on_scaleModeCombo_activated (int index) slot
Definition at line 660 of file imviewerControlPanel.cpp.
Referenced by imviewerForm::toggleUserBox().
on_scaleTypeCombo_activated
void imviewerControlPanel::on_scaleTypeCombo_activated (int ct) protected slot
Definition at line 524 of file imviewerControlPanel.cpp.
on_statsBoxButton_clicked
void imviewerControlPanel::on_statsBoxButton_clicked () slot
Definition at line 843 of file imviewerControlPanel.cpp.
on_view_center_clicked
void imviewerControlPanel::on_view_center_clicked () protected slot
Definition at line 365 of file imviewerControlPanel.cpp.
on_view_dl_clicked
void imviewerControlPanel::on_view_dl_clicked () protected slot
Definition at line 400 of file imviewerControlPanel.cpp.
on_view_down_clicked
void imviewerControlPanel::on_view_down_clicked () protected slot
Definition at line 395 of file imviewerControlPanel.cpp.
on_view_dr_clicked
void imviewerControlPanel::on_view_dr_clicked () protected slot
Definition at line 390 of file imviewerControlPanel.cpp.
on_view_left_clicked
void imviewerControlPanel::on_view_left_clicked () protected slot
Definition at line 405 of file imviewerControlPanel.cpp.
on_view_right_clicked
void imviewerControlPanel::on_view_right_clicked () protected slot
Definition at line 385 of file imviewerControlPanel.cpp.
on_view_ul_clicked
void imviewerControlPanel::on_view_ul_clicked () protected slot
Definition at line 370 of file imviewerControlPanel.cpp.
on_view_up_clicked
void imviewerControlPanel::on_view_up_clicked () protected slot
Definition at line 375 of file imviewerControlPanel.cpp.
on_view_ur_clicked
void imviewerControlPanel::on_view_ur_clicked () protected slot
Definition at line 380 of file imviewerControlPanel.cpp.
on_ViewViewModecheckBox_stateChanged
void imviewerControlPanel::on_ViewViewModecheckBox_stateChanged (int st) protected slot
Definition at line 328 of file imviewerControlPanel.cpp.
on_widthEntry_editingFinished
void imviewerControlPanel::on_widthEntry_editingFinished () protected slot
Definition at line 349 of file imviewerControlPanel.cpp.
on_xcenEntry_editingFinished
void imviewerControlPanel::on_xcenEntry_editingFinished () protected slot
Definition at line 339 of file imviewerControlPanel.cpp.
on_ycenEntry_editingFinished
void imviewerControlPanel::on_ycenEntry_editingFinished () protected slot
Definition at line 344 of file imviewerControlPanel.cpp.
on_Zoom16_clicked
void imviewerControlPanel::on_Zoom16_clicked () protected slot
Definition at line 241 of file imviewerControlPanel.cpp.
on_Zoom1_clicked
void imviewerControlPanel::on_Zoom1_clicked () protected slot
Definition at line 209 of file imviewerControlPanel.cpp.
on_Zoom2_clicked
void imviewerControlPanel::on_Zoom2_clicked () protected slot
Definition at line 217 of file imviewerControlPanel.cpp.
on_Zoom4_clicked
void imviewerControlPanel::on_Zoom4_clicked () protected slot
Definition at line 225 of file imviewerControlPanel.cpp.
on_Zoom8_clicked
void imviewerControlPanel::on_Zoom8_clicked () protected slot
Definition at line 233 of file imviewerControlPanel.cpp.
on_ZoomEntry_editingFinished
void imviewerControlPanel::on_ZoomEntry_editingFinished () protected slot
Definition at line 249 of file imviewerControlPanel.cpp.
on_ZoomSlider_valueChanged
void imviewerControlPanel::on_ZoomSlider_valueChanged (int value) protected slot
Definition at line 198 of file imviewerControlPanel.cpp.
set_pointerViewCen
void imviewerControlPanel::set_pointerViewCen (QPointF mp) slot
Definition at line 516 of file imviewerControlPanel.cpp.
Referenced by viewLeftClicked().
set_PointerViewMode
void imviewerControlPanel::set_PointerViewMode (int pvm) slot
Definition at line 474 of file imviewerControlPanel.cpp.
Referenced by on_pointerViewModecomboBox_activated().
set_ViewViewMode()
void imviewerControlPanel::set_ViewViewMode (int vvm)
Definition at line 273 of file imviewerControlPanel.cpp.
Referenced by enableViewViewMode().
setupCombos()
void imviewerControlPanel::setupCombos () protected
Definition at line 56 of file imviewerControlPanel.cpp.
Referenced by imviewerControlPanel().
setupMode()
void imviewerControlPanel::setupMode () protected
Definition at line 50 of file imviewerControlPanel.cpp.
Referenced by imviewerControlPanel().
update_biasEntry()
void imviewerControlPanel::update_biasEntry () protected
Definition at line 610 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_biasEntry_editingFinished(), on_biasSlider_valueChanged(), on_contrastEntry_editingFinished(), on_contrastSlider_valueChanged(), on_maxdatEntry_editingFinished(), on_maxdatSlider_valueChanged(), on_mindatEntry_editingFinished(), on_mindatSlider_valueChanged(), on_scaleModeCombo_activated(), and update_panel().
update_biasRelEntry()
void imviewerControlPanel::update_biasRelEntry () protected
Definition at line 620 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_scaleModeCombo_activated(), and update_panel().
update_biasSlider()
void imviewerControlPanel::update_biasSlider () protected
Definition at line 600 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_maxdatEntry_editingFinished(), on_mindatEntry_editingFinished(), and update_panel().
update_contrastEntry()
void imviewerControlPanel::update_contrastEntry () protected
Definition at line 640 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_biasEntry_editingFinished(), on_biasSlider_valueChanged(), on_contrastEntry_editingFinished(), on_contrastSlider_valueChanged(), on_maxdatSlider_valueChanged(), on_mindatEntry_editingFinished(), on_mindatSlider_valueChanged(), on_scaleModeCombo_activated(), and update_panel().
update_contrastRelEntry()
void imviewerControlPanel::update_contrastRelEntry () protected
Definition at line 650 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_scaleModeCombo_activated(), and update_panel().
update_contrastSlider()
void imviewerControlPanel::update_contrastSlider () protected
Definition at line 630 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_mindatEntry_editingFinished(), and update_panel().
update_maxdatEntry()
void imviewerControlPanel::update_maxdatEntry () protected
Definition at line 580 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_biasEntry_editingFinished(), on_biasSlider_valueChanged(), on_contrastEntry_editingFinished(), on_contrastSlider_valueChanged(), on_maxdatEntry_editingFinished(), on_maxdatSlider_valueChanged(), on_scaleModeCombo_activated(), and update_panel().
update_maxdatRelEntry()
void imviewerControlPanel::update_maxdatRelEntry () protected
Definition at line 590 of file imviewerControlPanel.cpp.
Referenced by on_scaleModeCombo_activated(), and update_panel().
update_maxdatSlider()
void imviewerControlPanel::update_maxdatSlider () protected
Definition at line 568 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_maxdatEntry_editingFinished(), and update_panel().
update_mindatEntry()
void imviewerControlPanel::update_mindatEntry () protected
Definition at line 548 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_biasEntry_editingFinished(), on_biasSlider_valueChanged(), on_contrastEntry_editingFinished(), on_contrastSlider_valueChanged(), on_mindatEntry_editingFinished(), on_mindatSlider_valueChanged(), on_scaleModeCombo_activated(), and update_panel().
update_mindatRelEntry()
void imviewerControlPanel::update_mindatRelEntry () protected
Definition at line 558 of file imviewerControlPanel.cpp.
Referenced by on_scaleModeCombo_activated(), and update_panel().
update_mindatSlider()
void imviewerControlPanel::update_mindatSlider () protected
Definition at line 537 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_mindatEntry_editingFinished(), and update_panel().
update_panel()
void imviewerControlPanel::update_panel ()
Definition at line 141 of file imviewerControlPanel.cpp.
Referenced by imviewerForm::change_center(), on_heightEntry_editingFinished(), on_widthEntry_editingFinished(), and imviewerForm::postChangeImdata().
update_whEntry()
void imviewerControlPanel::update_whEntry ()
Definition at line 312 of file imviewerControlPanel.cpp.
Referenced by init_panel(), and update_panel().
update_xycenEntry()
void imviewerControlPanel::update_xycenEntry ()
Referenced by init_panel(), and update_panel().
update_ZoomEntry()
void imviewerControlPanel::update_ZoomEntry ()
Definition at line 191 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_ZoomSlider_valueChanged(), and update_panel().
update_ZoomSlider()
void imviewerControlPanel::update_ZoomSlider ()
Definition at line 186 of file imviewerControlPanel.cpp.
Referenced by init_panel(), on_Zoom16_clicked(), on_Zoom1_clicked(), on_Zoom2_clicked(), on_Zoom4_clicked(), on_Zoom8_clicked(), on_ZoomEntry_editingFinished(), and update_panel().
updateMouseCoords()
void imviewerControlPanel::updateMouseCoords (double x, double y, double v)
Definition at line 410 of file imviewerControlPanel.cpp.
Referenced by imviewerForm::updateMouseCoords().
viewBoxMoved
void imviewerControlPanel::viewBoxMoved (const QRectF & newcen) slot
Definition at line 861 of file imviewerControlPanel.cpp.
Referenced by imviewerControlPanel().
viewLeftClicked()
void imviewerControlPanel::viewLeftClicked (QPointF mp)
Definition at line 461 of file imviewerControlPanel.cpp.
Referenced by imviewerForm::viewLeftClicked().
viewLeftPressed()
void imviewerControlPanel::viewLeftPressed (QPointF mp)
Definition at line 447 of file imviewerControlPanel.cpp.
Referenced by imviewerForm::viewLeftPressed().
Member Data Documentation
IgnorebiasSliderChange
bool imviewerControlPanel::IgnorebiasSliderChange protected
Definition at line 129 of file imviewerControlPanel.h.
Referenced by init_panel(), on_biasSlider_valueChanged(), update_biasSlider(), and update_panel().
IgnorecontrastSliderChange
bool imviewerControlPanel::IgnorecontrastSliderChange protected
Definition at line 134 of file imviewerControlPanel.h.
Referenced by init_panel(), on_contrastSlider_valueChanged(), update_contrastSlider(), and update_panel().
IgnoremaxdatSliderChange
bool imviewerControlPanel::IgnoremaxdatSliderChange protected
Definition at line 124 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), init_panel(), on_maxdatSlider_valueChanged(), update_maxdatSlider(), and update_panel().
IgnoremindatSliderChange
bool imviewerControlPanel::IgnoremindatSliderChange protected
Definition at line 119 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), init_panel(), on_mindatSlider_valueChanged(), update_mindatSlider(), and update_panel().
IgnoreZoomSliderChange
bool imviewerControlPanel::IgnoreZoomSliderChange protected
Definition at line 32 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), init_panel(), on_Zoom16_clicked(), on_Zoom1_clicked(), on_Zoom2_clicked(), on_Zoom4_clicked(), on_Zoom8_clicked(), on_ZoomEntry_editingFinished(), on_ZoomSlider_valueChanged(), and update_panel().
imv
imviewerForm* imviewerControlPanel::imv protected
Definition at line 20 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), init_panel(), on_biasEntry_editingFinished(), on_biasSlider_valueChanged(), on_colorbarCombo_activated(), on_contrastEntry_editingFinished(), on_contrastSlider_valueChanged(), on_heightEntry_editingFinished(), on_imtimerspinBox_valueChanged(), on_maxdatEntry_editingFinished(), on_maxdatSlider_valueChanged(), on_mindatEntry_editingFinished(), on_mindatSlider_valueChanged(), on_overZoom1_clicked(), on_overZoom2_clicked(), on_overZoom4_clicked(), on_scaleModeCombo_activated(), on_scaleTypeCombo_activated(), on_view_center_clicked(), on_view_dl_clicked(), on_view_down_clicked(), on_view_dr_clicked(), on_view_left_clicked(), on_view_right_clicked(), on_view_ul_clicked(), on_view_up_clicked(), on_view_ur_clicked(), on_widthEntry_editingFinished(), on_xcenEntry_editingFinished(), on_ycenEntry_editingFinished(), on_Zoom16_clicked(), on_Zoom1_clicked(), on_Zoom2_clicked(), on_Zoom4_clicked(), on_Zoom8_clicked(), on_ZoomEntry_editingFinished(), on_ZoomSlider_valueChanged(), set_PointerViewMode(), set_ViewViewMode(), update_biasEntry(), update_biasRelEntry(), update_biasSlider(), update_contrastEntry(), update_contrastRelEntry(), update_contrastSlider(), update_maxdatEntry(), update_maxdatRelEntry(), update_maxdatSlider(), update_mindatEntry(), update_mindatRelEntry(), update_mindatSlider(), update_panel(), update_whEntry(), update_ZoomEntry(), update_ZoomSlider(), updateMouseCoords(), viewBoxMoved(), and viewLeftPressed().
pointerViewCen
QPointF imviewerControlPanel::pointerViewCen
Definition at line 89 of file imviewerControlPanel.h.
Referenced by set_pointerViewCen(), and viewLeftPressed().
PointerViewEmpty
bool imviewerControlPanel::PointerViewEmpty protected
Definition at line 93 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), nullMouseCoords(), set_PointerViewMode(), updateMouseCoords(), viewLeftClicked(), and viewLeftPressed().
PointerViewFixed
bool imviewerControlPanel::PointerViewFixed protected
Definition at line 94 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), nullMouseCoords(), on_pointerSetLocButton_clicked(), set_pointerViewCen(), updateMouseCoords(), and viewLeftPressed().
PointerViewMode
int imviewerControlPanel::PointerViewMode
Definition at line 90 of file imviewerControlPanel.h.
Referenced by set_PointerViewMode(), setupMode(), updateMouseCoords(), viewLeftClicked(), and viewLeftPressed().
PointerViewWaiting
bool imviewerControlPanel::PointerViewWaiting protected
Definition at line 95 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), on_pointerSetLocButton_clicked(), set_pointerViewCen(), and viewLeftClicked().
qgs_empty
QGraphicsScene* imviewerControlPanel::qgs_empty
Definition at line 54 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), nullMouseCoords(), set_PointerViewMode(), and viewLeftClicked().
qgs_view
QGraphicsScene* imviewerControlPanel::qgs_view
Definition at line 53 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), imviewerForm::postChangeImdata(), and set_ViewViewMode().
qpmi_view
QGraphicsPixmapItem* imviewerControlPanel::qpmi_view
Definition at line 55 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), imviewerForm::postChangeImdata(), set_ViewViewMode(), and viewBoxMoved().
statsBoxButtonState
bool imviewerControlPanel::statsBoxButtonState
Definition at line 157 of file imviewerControlPanel.h.
Referenced by imviewerControlPanel(), on_statsBoxButton_clicked(), and imviewerForm::toggleStatsBox().
ui
Ui::imviewerControlPanel imviewerControlPanel::ui
Definition at line 168 of file imviewerControlPanel.h.
Referenced by imviewerForm::change_center(), imviewerControlPanel(), init_panel(), nullMouseCoords(), on_biasEntry_editingFinished(), on_biasSlider_valueChanged(), on_contrastEntry_editingFinished(), on_contrastSlider_valueChanged(), on_heightEntry_editingFinished(), on_maxdatEntry_editingFinished(), on_maxdatSlider_valueChanged(), on_mindatEntry_editingFinished(), on_mindatSlider_valueChanged(), on_pointerSetLocButton_clicked(), on_statsBoxButton_clicked(), on_widthEntry_editingFinished(), on_xcenEntry_editingFinished(), on_ycenEntry_editingFinished(), on_ZoomEntry_editingFinished(), on_ZoomSlider_valueChanged(), imviewerForm::post_zoomLevel(), imviewerForm::postSetImsize(), set_pointerViewCen(), set_PointerViewMode(), set_ViewViewMode(), setupCombos(), imviewerForm::toggleStatsBox(), update_biasEntry(), update_biasRelEntry(), update_biasSlider(), update_contrastEntry(), update_contrastRelEntry(), update_contrastSlider(), update_maxdatEntry(), update_maxdatRelEntry(), update_maxdatSlider(), update_mindatEntry(), update_mindatRelEntry(), update_mindatSlider(), update_panel(), update_whEntry(), update_ZoomEntry(), update_ZoomSlider(), updateMouseCoords(), viewLeftClicked(), and viewLeftPressed().
viewBox
StretchBox* imviewerControlPanel::viewBox
Definition at line 59 of file imviewerControlPanel.h.
Referenced by imviewerForm::change_center(), imviewerControlPanel(), set_ViewViewMode(), and viewBoxMoved().
viewLineHorz
QGraphicsLineItem* imviewerControlPanel::viewLineHorz
Definition at line 57 of file imviewerControlPanel.h.
Referenced by imviewerForm::change_center(), and imviewerControlPanel().
viewLineVert
QGraphicsLineItem* imviewerControlPanel::viewLineVert
Definition at line 56 of file imviewerControlPanel.h.
Referenced by imviewerForm::change_center(), imviewerControlPanel(), imviewerForm::postChangeImdata(), and set_ViewViewMode().
ViewViewMode
int imviewerControlPanel::ViewViewMode
Definition at line 61 of file imviewerControlPanel.h.
Referenced by imviewerForm::postChangeImdata(), set_ViewViewMode(), and setupMode().
The documentation for this class was generated from the following files:
/home/jrmales/Source/c/rtimv/src/imviewerControlPanel.h
/home/jrmales/Source/c/rtimv/src/imviewerControlPanel.cpp