rtimv: imviewer Class Reference
imviewer Class Reference
#include <imviewer.hpp>
Public Slots
void handleSigSegv ()
Public Member Functions
imviewer (const std::vector< std::string > &shkeys, QWidget *Parent=0, Qt::WindowFlags f=0)
QPixmap * getPixmap ()
Get the QPixMap pointer.
void changeImdata (bool newdata=false)
Updates the QImage and basic statistics after a new image.
virtual void postChangeImdata ()
to call after change imdata does its work.
float get_imdat_min ()
float get_imdat_max ()
float zoomLevel ()
float zoomLevelMin ()
float zoomLevelMax ()
void zoomLevel (float zl)
virtual void post_zoomLevel ()
void set_RealTimeEnabled (int)
void set_RealTimeStopped (int)
virtual void updateFPS ()
Called whenever the displayed image updates its FPS.
virtual void updateAge ()
Called whenever the displayed image updates its Age.
Static Public Member Functions
static void st_handleSigSegv (int signum, siginfo_t *siginf, void *ucont)
Protected Member Functions
virtual void onConnect ()
Protected Attributes
QImage * m_qim {nullptr}
A QT image, used to store the color-map encoded data.
QPixmap m_qpm
A QT pixmap, used to prep the QImage for display.
bool amChangingimdata
float sat_level {1e30}
int saturated {0}
float imdat_min
float imdat_max
float m_zoomLevel {1}
float m_zoomLevelMin {0.125}
float m_zoomLevelMax {64}
bool RealTimeEnabled {true}
Controls whether imviewer is using real-time data.
bool RealTimeStopped {false}
Set when user temporarily freezes real-time data viewing.
Image Filtering
float * m_lowPassFiltered {nullptr}
bool m_applyLPFilter
int m_lpFilterType
Private Attributes
QSocketNotifier * snSegv
Static Private Attributes
static int sigsegvFd [2]
Image Data
uint32_t m_nx {0}
The number of pixels in the x (horizontal) direction.
uint32_t m_ny {0}
The number of pixels in the y (vertical) direction.
std::vector< rtimvImage * > m_images
void setImsize (uint32_t x, uint32_t y)
virtual void postSetImsize ()
Changes the image size, but only if necessary.
uint32_t nx ()
Get the number of x pixels.
uint32_t ny ()
Get the number of y pixels.
Image Data Update Interval
QTimer m_timer
When this times out imviewer checks for a new image.
int m_timeout {100}
The timeout for checking for a new images, ms.
void timeout (int to)
Set the image display timeout.
void timerout ()
Function called by m_timer expiration.
Calibrated Pixel Access
Settings to control which calibrations are applied, and provided acccess to calibrated pixels.
Calibrations include dark subtraction, reference subtraction, flat field, mask, and low and high pass filtering. Note: only dark subtraction and masking are currently implemented.
The pixelF function pointer is used so that only a single if-else tree needs to be evaluated before iterating over all pixels. The pixel() function returns a pointer to the static pixel_* function appropriate for the current calibration settings.
typedef float(* pixelF) (imviewer *, size_t)
The fuction pointer type for accessing pixels with calibrations applied.
bool m_subtractDark {false}
bool m_applyMask {false}
bool m_applySatMask {false}
pixelF pixel ()
Returns a pointer to the static pixel value calculation function for the current calibration configuration.
static float pixel_noCal (imviewer *imv, size_t idx)
Access pixels with no calibrations applied.
static float pixel_subDark (imviewer *imv, size_t idx)
Access pixels with dark subtraction applied.
static float pixel_applyMask (imviewer *imv, size_t idx)
Access pixels with the mask applied.
static float pixel_subDarkApplyMask (imviewer *imv, size_t idx)
Access pixels with dark subtraction and masking applied.
Colorbar Selection
enum en_cbStretches {
stretchLinear, stretchLog, stretchPow, stretchSqrt,
stretchSquare, cbStretches_max
}
enum colorbars {
colorbarGrey, colorbarJet, colorbarHot, colorbarBone,
colorbarRed, colorbarGreen, colorbarBlue, colorbarMax
}
enum colorbar_modes {
minmaxglobal, minmaxview, minmaxbox, user,
colorbar_modes_max
}
typedef int(* pixelIndexF) (float)
int m_mincol {0}
The minimum index to use for the color table.
int m_maxcol {253}
The maximum index to use for the color table.
int m_maskcol {254}
The index in the color table to use for the mask color.
int m_satcol {255}
The index in the color table to use for the saturation color.
int colorbar_mode {minmaxglobal}
int m_cbStretch {stretchLinear}
int current_colorbar {colorbarBone}
QColor warning_color
void load_colorbar (int)
int get_current_colorbar ()
void set_colorbar_mode (int mode)
int get_colorbar_mode ()
void set_cbStretch (int)
int get_cbStretch ()
pixelIndexF pixelIndex ()
static int pixelIndex_linear (float d)
static int pixelIndex_log (float d)
static int pixelIndex_pow (float d)
static int pixelIndex_sqrt (float d)
static int pixelIndex_square (float d)
Colorbar Scale Control
float m_mindat
The minimum data value used for scaling.
float m_maxdat
The maximum data valuse used for scaling.
bool m_autoScale {false}
void mindat (float md)
float mindat ()
void maxdat (float md)
float maxdat ()
void bias (float b)
float bias ()
void bias_rel (float b)
float bias_rel ()
void contrast (float c)
float contrast ()
void contrast_rel (float cr)
float contrast_rel ()
int calcPixIndex (float d)
Calculates the color map index of a value.
A User Defined Region
int userBoxActive {0}
int64_t userBox_i0
int64_t userBox_i1
int64_t userBox_j0
int64_t userBox_j1
int64_t guideBox_i0
int64_t guideBox_i1
int64_t guideBox_j0
int64_t guideBox_j1
float userBox_max
float userBox_min
int getUserBoxActive ()
void setUserBoxActive (bool usba)
Detailed Description
Definition at line 42 of file imviewer.hpp.
Member Typedef Documentation
pixelF
typedef float(* imviewer::pixelF) (imviewer *, size_t)
The fuction pointer type for accessing pixels with calibrations applied.
Definition at line 126 of file imviewer.hpp.
pixelIndexF
typedef int(* imviewer::pixelIndexF) (float)
Definition at line 184 of file imviewer.hpp.
Member Enumeration Documentation
colorbar_modes
enum imviewer::colorbar_modes
Enumerator
minmaxglobal
minmaxview
minmaxbox
user
colorbar_modes_max
Definition at line 218 of file imviewer.hpp.
colorbars
enum imviewer::colorbars
Enumerator
colorbarGrey
colorbarJet
colorbarHot
colorbarBone
colorbarRed
colorbarGreen
colorbarBlue
colorbarMax
Definition at line 214 of file imviewer.hpp.
en_cbStretches
enum imviewer::en_cbStretches
Enumerator
stretchLinear
The pixel values are scaled linearly to between m_mindat and m_maxdat.
stretchLog
The pixel values are scaled logarithmically between m_mindat and m_maxdat.
stretchPow
the pixel values are scaled as between m_mindat and m_maxdat
stretchSqrt
the pixel values are scaled as between m_mindat and m_maxdat
stretchSquare
the pixel values are scaled as between m_mindat and m_maxdat
cbStretches_max
Definition at line 186 of file imviewer.hpp.
Constructor & Destructor Documentation
imviewer()
imviewer::imviewer (const std::vector< std::string > & shkeys, QWidget * Parent = 0, Qt::WindowFlags f = 0)
Definition at line 8 of file imviewer.cpp.
Member Function Documentation
bias() [1/2]
void imviewer::bias (float b)
Definition at line 314 of file imviewer.cpp.
Referenced by imviewerControlPanel::on_biasEntry_editingFinished().
bias() [2/2]
float imviewer::bias ()
Definition at line 322 of file imviewer.cpp.
Referenced by contrast(), contrast_rel(), imviewerForm::updateMouseCoords(), and imviewerForm::viewRightPressed().
bias_rel() [1/2]
void imviewer::bias_rel (float b)
Definition at line 327 of file imviewer.cpp.
Referenced by imviewerControlPanel::on_biasSlider_valueChanged().
bias_rel() [2/2]
float imviewer::bias_rel ()
Definition at line 335 of file imviewer.cpp.
calcPixIndex()
int imviewer::calcPixIndex (float d) protected
Calculates the color map index of a value.
Returned value includes the effect of the current color bar stretch (m_mindat and m_maxdat) and the current color bar scale (m_colorbarScale)
Definition at line 364 of file imviewer.cpp.
Referenced by changeImdata().
changeImdata()
void imviewer::changeImdata (bool newdata = false)
Updates the QImage and basic statistics after a new image.
Parameters
newdata determines whether statistics are calculated (true) or not (false).
Definition at line 399 of file imviewer.cpp.
Referenced by getPixmap(), load_colorbar(), imviewerControlPanel::on_biasEntry_editingFinished(), imviewerControlPanel::on_biasSlider_valueChanged(), imviewerControlPanel::on_contrastEntry_editingFinished(), imviewerControlPanel::on_contrastSlider_valueChanged(), imviewerControlPanel::on_maxdatEntry_editingFinished(), imviewerControlPanel::on_maxdatSlider_valueChanged(), imviewerControlPanel::on_mindatEntry_editingFinished(), imviewerControlPanel::on_mindatSlider_valueChanged(), imviewerControlPanel::on_scaleModeCombo_activated(), imviewerControlPanel::on_scaleTypeCombo_activated(), imviewerForm::reStretch(), imviewerForm::setApplyMask(), imviewerForm::setApplySatMask(), imviewerForm::setDarkSub(), setUserBoxActive(), timerout(), and imviewerForm::updateMouseCoords().
contrast() [1/2]
void imviewer::contrast (float c)
Definition at line 340 of file imviewer.cpp.
Referenced by imviewerControlPanel::on_contrastEntry_editingFinished(), and imviewerControlPanel::on_contrastSlider_valueChanged().
contrast() [2/2]
float imviewer::contrast ()
Definition at line 347 of file imviewer.cpp.
Referenced by bias(), bias_rel(), imviewerForm::updateMouseCoords(), and imviewerForm::viewRightPressed().
contrast_rel() [1/2]
void imviewer::contrast_rel (float cr)
Definition at line 357 of file imviewer.cpp.
contrast_rel() [2/2]
float imviewer::contrast_rel ()
Definition at line 352 of file imviewer.cpp.
get_cbStretch()
int imviewer::get_cbStretch ()
Definition at line 288 of file imviewer.cpp.
Referenced by get_colorbar_mode(), imviewerControlPanel::init_panel(), imviewerForm::toggleLogLinear(), and imviewerControlPanel::update_panel().
get_colorbar_mode()
int imviewer::get_colorbar_mode () inline
Definition at line 220 of file imviewer.hpp.
Referenced by imviewerControlPanel::init_panel(), imviewerForm::reStretch(), and imviewerControlPanel::update_panel().
get_current_colorbar()
int imviewer::get_current_colorbar () inline
Definition at line 216 of file imviewer.hpp.
Referenced by imviewerControlPanel::init_panel(), and imviewerControlPanel::update_panel().
get_imdat_max()
float imviewer::get_imdat_max () inline
Definition at line 340 of file imviewer.hpp.
Referenced by imviewerControlPanel::on_contrastSlider_valueChanged(), imviewerControlPanel::on_maxdatSlider_valueChanged(), imviewerControlPanel::on_mindatSlider_valueChanged(), imviewerControlPanel::on_scaleModeCombo_activated(), imviewerForm::reStretch(), imviewerControlPanel::update_biasRelEntry(), imviewerControlPanel::update_biasSlider(), imviewerControlPanel::update_contrastRelEntry(), imviewerControlPanel::update_contrastSlider(), imviewerControlPanel::update_maxdatRelEntry(), imviewerControlPanel::update_maxdatSlider(), imviewerControlPanel::update_mindatRelEntry(), and imviewerControlPanel::update_mindatSlider().
get_imdat_min()
float imviewer::get_imdat_min () inline
Definition at line 339 of file imviewer.hpp.
Referenced by imviewerControlPanel::on_contrastSlider_valueChanged(), imviewerControlPanel::on_maxdatSlider_valueChanged(), imviewerControlPanel::on_mindatSlider_valueChanged(), imviewerControlPanel::on_scaleModeCombo_activated(), imviewerForm::reStretch(), imviewerControlPanel::update_biasRelEntry(), imviewerControlPanel::update_biasSlider(), imviewerControlPanel::update_contrastRelEntry(), imviewerControlPanel::update_contrastSlider(), imviewerControlPanel::update_maxdatRelEntry(), imviewerControlPanel::update_maxdatSlider(), imviewerControlPanel::update_mindatRelEntry(), and imviewerControlPanel::update_mindatSlider().
getPixmap()
QPixmap* imviewer::getPixmap () inline
Get the QPixMap pointer.
Definition at line 316 of file imviewer.hpp.
Referenced by imviewerControlPanel::imviewerControlPanel(), and imviewerControlPanel::set_ViewViewMode().
getUserBoxActive()
int imviewer::getUserBoxActive () inline
Definition at line 380 of file imviewer.hpp.
handleSigSegv
void imviewer::handleSigSegv () slot
Definition at line 703 of file imviewer.cpp.
Referenced by imviewer().
load_colorbar()
void imviewer::load_colorbar (int cb)
Definition at line 229 of file imviewer.cpp.
Referenced by imviewerControlPanel::on_colorbarCombo_activated(), and setImsize().
maxdat() [1/2]
void imviewer::maxdat (float md)
Definition at line 304 of file imviewer.cpp.
Referenced by imviewerControlPanel::on_maxdatEntry_editingFinished(), imviewerControlPanel::on_maxdatSlider_valueChanged(), imviewerControlPanel::on_scaleModeCombo_activated(), imviewerControlPanel::update_biasEntry(), imviewerControlPanel::update_biasRelEntry(), imviewerControlPanel::update_biasSlider(), imviewerControlPanel::update_contrastEntry(), imviewerControlPanel::update_contrastRelEntry(), imviewerControlPanel::update_contrastSlider(), imviewerControlPanel::update_maxdatEntry(), imviewerControlPanel::update_maxdatRelEntry(), and imviewerControlPanel::update_maxdatSlider().
maxdat() [2/2]
float imviewer::maxdat ()
Definition at line 309 of file imviewer.cpp.
Referenced by bias(), bias_rel(), changeImdata(), contrast(), contrast_rel(), imviewerForm::imviewerForm(), imviewerForm::reStretch(), and setUserBoxActive().
mindat() [1/2]
void imviewer::mindat (float md)
Definition at line 293 of file imviewer.cpp.
Referenced by imviewerControlPanel::on_mindatEntry_editingFinished(), imviewerControlPanel::on_mindatSlider_valueChanged(), imviewerControlPanel::on_scaleModeCombo_activated(), imviewerControlPanel::update_biasEntry(), imviewerControlPanel::update_biasRelEntry(), imviewerControlPanel::update_biasSlider(), imviewerControlPanel::update_contrastEntry(), imviewerControlPanel::update_contrastRelEntry(), imviewerControlPanel::update_contrastSlider(), imviewerControlPanel::update_mindatEntry(), imviewerControlPanel::update_mindatRelEntry(), and imviewerControlPanel::update_mindatSlider().
mindat() [2/2]
float imviewer::mindat ()
Definition at line 298 of file imviewer.cpp.
Referenced by bias(), bias_rel(), changeImdata(), contrast(), contrast_rel(), imviewerForm::imviewerForm(), imviewerForm::reStretch(), and setUserBoxActive().
nx()
uint32_t imviewer::nx ()
Get the number of x pixels.
Returns
the current vvalue of m_nx
Definition at line 91 of file imviewer.cpp.
Referenced by imviewerControlPanel::imviewerControlPanel(), imviewerControlPanel::on_widthEntry_editingFinished(), imviewerControlPanel::on_xcenEntry_editingFinished(), imviewerControlPanel::set_ViewViewMode(), imviewerForm::setTarget(), imviewerForm::squareDown(), imviewerForm::squareUp(), imviewerControlPanel::update_whEntry(), imviewerControlPanel::viewBoxMoved(), and imviewerControlPanel::viewLeftPressed().
ny()
uint32_t imviewer::ny ()
Get the number of y pixels.
Returns
the current vvalue of m_ny
Definition at line 96 of file imviewer.cpp.
Referenced by imviewerControlPanel::imviewerControlPanel(), imviewerControlPanel::on_heightEntry_editingFinished(), imviewerControlPanel::on_ycenEntry_editingFinished(), imviewerForm::setTarget(), imviewerForm::squareDown(), imviewerForm::squareUp(), imviewerControlPanel::update_whEntry(), imviewerControlPanel::updateMouseCoords(), and imviewerControlPanel::viewLeftPressed().
onConnect()
virtual void imviewer::onConnect () inline protected virtual
Reimplemented in imviewerForm.
Definition at line 83 of file imviewer.hpp.
Referenced by timerout().
pixel()
imviewer::pixelF imviewer::pixel ()
Returns a pointer to the static pixel value calculation function for the current calibration configuration.
Calibration configuration includes the value of m_subtractDark, m_applyMask.
Returns
a pointer to one of pixel_noCal, pixel_subDark, pixel_applyMask, pixel_subDarkApplyMask.
Definition at line 149 of file imviewer.cpp.
Referenced by changeImdata(), setUserBoxActive(), and imviewerForm::updateMouseCoords().
pixel_applyMask()
float imviewer::pixel_applyMask (imviewer * imv, size_t idx) static
Access pixels with the mask applied.
Returns
the value of pixel idx after applying the mask
Parameters
[in] imv the imviewer instance to access
[in] idx the linear pixel number to access
Definition at line 215 of file imviewer.cpp.
Referenced by pixel().
pixel_noCal()
float imviewer::pixel_noCal (imviewer * imv, size_t idx) static
Access pixels with no calibrations applied.
Returns
the value of pixel idx
Parameters
[in] imv the imviewer instance to access
[in] idx the linear pixel number to access
Definition at line 201 of file imviewer.cpp.
Referenced by pixel().
pixel_subDark()
float imviewer::pixel_subDark (imviewer * imv, size_t idx) static
Access pixels with dark subtraction applied.
Returns
the value of pixel idx after dark subtraction
Parameters
[in] imv the imviewer instance to access
[in] idx the linear pixel number to access
Definition at line 208 of file imviewer.cpp.
Referenced by pixel().
pixel_subDarkApplyMask()
float imviewer::pixel_subDarkApplyMask (imviewer * imv, size_t idx) static
Access pixels with dark subtraction and masking applied.
Returns
the value of pixel idx after subtracting the dark and applying the mask
Parameters
[in] imv the imviewer instance to access
[in] idx the linear pixel number to access
Definition at line 222 of file imviewer.cpp.
Referenced by pixel().
pixelIndex()
pixelIndexF imviewer::pixelIndex ()
Referenced by get_colorbar_mode().
pixelIndex_linear()
static int imviewer::pixelIndex_linear (float d) static
Referenced by get_colorbar_mode().
pixelIndex_log()
static int imviewer::pixelIndex_log (float d) static
Referenced by get_colorbar_mode().
pixelIndex_pow()
static int imviewer::pixelIndex_pow (float d) static
Referenced by get_colorbar_mode().
pixelIndex_sqrt()
static int imviewer::pixelIndex_sqrt (float d) static
Referenced by get_colorbar_mode().
pixelIndex_square()
static int imviewer::pixelIndex_square (float d) static
Referenced by get_colorbar_mode().
post_zoomLevel()
void imviewer::post_zoomLevel () virtual
Reimplemented in imviewerForm.
Definition at line 588 of file imviewer.cpp.
Referenced by zoomLevel(), and zoomLevelMax().
postChangeImdata()
void imviewer::postChangeImdata () virtual
to call after change imdata does its work.
Reimplemented in imviewerForm.
Definition at line 573 of file imviewer.cpp.
Referenced by changeImdata(), and getPixmap().
postSetImsize()
void imviewer::postSetImsize () virtual
Changes the image size, but only if necessary.
to call after set_imsize to handle allocations for derived classes
Reimplemented in imviewerForm.
Definition at line 86 of file imviewer.cpp.
Referenced by setImsize().
set_cbStretch()
void imviewer::set_cbStretch (int ct)
Definition at line 277 of file imviewer.cpp.
Referenced by get_colorbar_mode(), imviewerControlPanel::on_scaleTypeCombo_activated(), and imviewerForm::toggleLogLinear().
set_colorbar_mode()
void imviewer::set_colorbar_mode (int mode) inline
Definition at line 219 of file imviewer.hpp.
Referenced by imviewerControlPanel::on_biasEntry_editingFinished(), imviewerControlPanel::on_biasSlider_valueChanged(), imviewerControlPanel::on_contrastEntry_editingFinished(), imviewerControlPanel::on_contrastSlider_valueChanged(), imviewerControlPanel::on_maxdatEntry_editingFinished(), imviewerControlPanel::on_maxdatSlider_valueChanged(), imviewerControlPanel::on_mindatEntry_editingFinished(), imviewerControlPanel::on_mindatSlider_valueChanged(), imviewerControlPanel::on_scaleModeCombo_activated(), imviewerForm::reStretch(), and setUserBoxActive().
set_RealTimeEnabled()
void imviewer::set_RealTimeEnabled (int rte)
Definition at line 659 of file imviewer.cpp.
set_RealTimeStopped()
void imviewer::set_RealTimeStopped (int rts)
Definition at line 664 of file imviewer.cpp.
Referenced by imviewerForm::freezeRealTime().
setImsize()
void imviewer::setImsize (uint32_t x, uint32_t y)
Definition at line 61 of file imviewer.cpp.
Referenced by changeImdata().
setUserBoxActive()
void imviewer::setUserBoxActive (bool usba)
Definition at line 594 of file imviewer.cpp.
Referenced by getUserBoxActive(), imviewerControlPanel::on_biasEntry_editingFinished(), imviewerControlPanel::on_biasSlider_valueChanged(), imviewerControlPanel::on_contrastEntry_editingFinished(), imviewerControlPanel::on_contrastSlider_valueChanged(), imviewerControlPanel::on_maxdatEntry_editingFinished(), imviewerControlPanel::on_maxdatSlider_valueChanged(), imviewerControlPanel::on_mindatEntry_editingFinished(), imviewerControlPanel::on_mindatSlider_valueChanged(), imviewerControlPanel::on_scaleModeCombo_activated(), imviewerForm::toggleUserBox(), and imviewerForm::userBoxMoved().
st_handleSigSegv()
void imviewer::st_handleSigSegv (int signum, siginfo_t * siginf, void * ucont) static
Definition at line 688 of file imviewer.cpp.
Referenced by imviewer().
timeout()
void imviewer::timeout (int to)
Set the image display timeout.
This sets the display frame rate, e.g. a timeout of 100 msec will cause the display to update at 10 f.p.s.
Parameters
[in] to the new image display timeout
Definition at line 137 of file imviewer.cpp.
Referenced by imviewer(), and imviewerControlPanel::on_imtimerspinBox_valueChanged().
timerout
void imviewer::timerout () protected slot
Function called by m_timer expiration.
This is what actually checks for image data updates.
Definition at line 101 of file imviewer.cpp.
Referenced by imviewer().
updateAge()
void imviewer::updateAge () virtual
Called whenever the displayed image updates its Age.
Reimplemented in imviewerForm.
Definition at line 683 of file imviewer.cpp.
Referenced by timerout().
updateFPS()
void imviewer::updateFPS () virtual
Called whenever the displayed image updates its FPS.
Reimplemented in imviewerForm.
Definition at line 678 of file imviewer.cpp.
Referenced by timerout().
zoomLevel() [1/2]
float imviewer::zoomLevel () inline
Definition at line 349 of file imviewer.hpp.
Referenced by imviewerForm::keyPressEvent(), imviewerControlPanel::on_heightEntry_editingFinished(), imviewerControlPanel::on_view_dl_clicked(), imviewerControlPanel::on_view_down_clicked(), imviewerControlPanel::on_view_dr_clicked(), imviewerControlPanel::on_view_left_clicked(), imviewerControlPanel::on_view_right_clicked(), imviewerControlPanel::on_view_ul_clicked(), imviewerControlPanel::on_view_up_clicked(), imviewerControlPanel::on_view_ur_clicked(), imviewerControlPanel::on_widthEntry_editingFinished(), imviewerControlPanel::on_Zoom16_clicked(), imviewerControlPanel::on_Zoom1_clicked(), imviewerControlPanel::on_Zoom2_clicked(), imviewerControlPanel::on_Zoom4_clicked(), imviewerControlPanel::on_Zoom8_clicked(), imviewerControlPanel::on_ZoomEntry_editingFinished(), imviewerControlPanel::on_ZoomSlider_valueChanged(), imviewerForm::onWheelMoved(), imviewerForm::postSetImsize(), imviewerControlPanel::update_whEntry(), imviewerControlPanel::update_ZoomEntry(), imviewerControlPanel::update_ZoomSlider(), and zoomLevelMax().
zoomLevel() [2/2]
void imviewer::zoomLevel (float zl)
Definition at line 578 of file imviewer.cpp.
zoomLevelMax()
float imviewer::zoomLevelMax () inline
Definition at line 351 of file imviewer.hpp.
Referenced by imviewerControlPanel::on_ZoomSlider_valueChanged(), and imviewerControlPanel::update_ZoomSlider().
zoomLevelMin()
float imviewer::zoomLevelMin () inline
Definition at line 350 of file imviewer.hpp.
Referenced by imviewerControlPanel::on_ZoomSlider_valueChanged(), and imviewerControlPanel::update_ZoomSlider().
Member Data Documentation
amChangingimdata
bool imviewer::amChangingimdata protected
Definition at line 311 of file imviewer.hpp.
Referenced by changeImdata(), handleSigSegv(), and imviewerForm::updateMouseCoords().
colorbar_mode
int imviewer::colorbar_mode {minmaxglobal} protected
Definition at line 203 of file imviewer.hpp.
Referenced by get_colorbar_mode(), and set_colorbar_mode().
current_colorbar
int imviewer::current_colorbar {colorbarBone} protected
Definition at line 206 of file imviewer.hpp.
Referenced by get_current_colorbar(), load_colorbar(), and setImsize().
guideBox_i0
int64_t imviewer::guideBox_i0 protected
Definition at line 371 of file imviewer.hpp.
Referenced by imviewerForm::guideBoxMoved().
guideBox_i1
int64_t imviewer::guideBox_i1 protected
Definition at line 372 of file imviewer.hpp.
Referenced by imviewerForm::guideBoxMoved().
guideBox_j0
int64_t imviewer::guideBox_j0 protected
Definition at line 373 of file imviewer.hpp.
Referenced by imviewerForm::guideBoxMoved().
guideBox_j1
int64_t imviewer::guideBox_j1 protected
Definition at line 374 of file imviewer.hpp.
Referenced by imviewerForm::guideBoxMoved().
imdat_max
float imviewer::imdat_max protected
Definition at line 336 of file imviewer.hpp.
Referenced by bias_rel(), changeImdata(), contrast_rel(), get_imdat_max(), and imviewerForm::updateMouseCoords().
imdat_min
float imviewer::imdat_min protected
Definition at line 335 of file imviewer.hpp.
Referenced by bias_rel(), changeImdata(), contrast_rel(), get_imdat_min(), and imviewerForm::updateMouseCoords().
m_applyLPFilter
bool imviewer::m_applyLPFilter protected
Definition at line 297 of file imviewer.hpp.
m_applyMask
bool imviewer::m_applyMask {false}
Definition at line 132 of file imviewer.hpp.
Referenced by changeImdata(), pixel(), imviewerForm::setApplyMask(), and imviewerForm::toggleApplyMask().
m_applySatMask
bool imviewer::m_applySatMask {false}
Definition at line 134 of file imviewer.hpp.
Referenced by changeImdata(), imviewerForm::setApplySatMask(), and imviewerForm::toggleApplySatMask().
m_autoScale
bool imviewer::m_autoScale {false} protected
Definition at line 251 of file imviewer.hpp.
Referenced by changeImdata(), imviewerForm::setAutoScale(), and imviewerForm::toggleAutoScale().
m_cbStretch
int imviewer::m_cbStretch {stretchLinear} protected
Definition at line 204 of file imviewer.hpp.
Referenced by calcPixIndex(), get_cbStretch(), and set_cbStretch().
m_images
std::vector<rtimvImage *> imviewer::m_images protected
Definition at line 61 of file imviewer.hpp.
Referenced by changeImdata(), handleSigSegv(), imviewer(), pixel(), pixel_applyMask(), pixel_noCal(), pixel_subDark(), pixel_subDarkApplyMask(), timeout(), timerout(), and imviewerForm::updateAge().
m_lowPassFiltered
float* imviewer::m_lowPassFiltered {nullptr} protected
Definition at line 295 of file imviewer.hpp.
m_lpFilterType
int imviewer::m_lpFilterType protected
Definition at line 299 of file imviewer.hpp.
m_maskcol
int imviewer::m_maskcol {254} protected
The index in the color table to use for the mask color.
Definition at line 199 of file imviewer.hpp.
Referenced by changeImdata(), and load_colorbar().
m_maxcol
int imviewer::m_maxcol {253} protected
The maximum index to use for the color table.
Definition at line 197 of file imviewer.hpp.
Referenced by calcPixIndex(), and load_colorbar().
m_maxdat
float imviewer::m_maxdat protected
The maximum data valuse used for scaling.
Definition at line 249 of file imviewer.hpp.
Referenced by bias(), bias_rel(), calcPixIndex(), changeImdata(), contrast(), contrast_rel(), and maxdat().
m_mincol
int imviewer::m_mincol {0} protected
The minimum index to use for the color table.
Definition at line 195 of file imviewer.hpp.
Referenced by calcPixIndex(), and load_colorbar().
m_mindat
float imviewer::m_mindat protected
The minimum data value used for scaling.
Definition at line 247 of file imviewer.hpp.
Referenced by bias(), bias_rel(), calcPixIndex(), changeImdata(), contrast(), contrast_rel(), and mindat().
m_nx
uint32_t imviewer::m_nx {0} protected
The number of pixels in the x (horizontal) direction.
Definition at line 58 of file imviewer.hpp.
Referenced by imviewerForm::change_center(), changeImdata(), nx(), pixel(), imviewerForm::post_zoomLevel(), imviewerForm::postSetImsize(), imviewerForm::resizeEvent(), setImsize(), setUserBoxActive(), and imviewerForm::updateMouseCoords().
m_ny
uint32_t imviewer::m_ny {0} protected
The number of pixels in the y (vertical) direction.
Definition at line 59 of file imviewer.hpp.
Referenced by imviewerForm::change_center(), changeImdata(), imviewerForm::guideBoxMoved(), ny(), pixel(), imviewerForm::post_zoomLevel(), imviewerForm::postSetImsize(), imviewerForm::resizeEvent(), setImsize(), setUserBoxActive(), imviewerForm::updateMouseCoords(), and imviewerForm::userBoxMoved().
m_qim
QImage* imviewer::m_qim {nullptr} protected
A QT image, used to store the color-map encoded data.
Definition at line 307 of file imviewer.hpp.
Referenced by changeImdata(), load_colorbar(), and setImsize().
m_qpm
QPixmap imviewer::m_qpm protected
A QT pixmap, used to prep the QImage for display.
Definition at line 309 of file imviewer.hpp.
Referenced by changeImdata(), getPixmap(), and imviewerForm::postChangeImdata().
m_satcol
int imviewer::m_satcol {255} protected
The index in the color table to use for the saturation color.
Definition at line 201 of file imviewer.hpp.
Referenced by changeImdata(), and load_colorbar().
m_subtractDark
bool imviewer::m_subtractDark {false}
Definition at line 130 of file imviewer.hpp.
Referenced by pixel(), imviewerForm::setDarkSub(), and imviewerForm::toggleDarkSub().
m_timeout
int imviewer::m_timeout {100} protected
The timeout for checking for a new images, ms.
Definition at line 92 of file imviewer.hpp.
Referenced by imviewerForm::imviewerForm(), and set_RealTimeStopped().
m_timer
QTimer imviewer::m_timer protected
When this times out imviewer checks for a new image.
Definition at line 90 of file imviewer.hpp.
Referenced by imviewer(), imviewerForm::imviewerForm(), set_RealTimeStopped(), and timeout().
m_zoomLevel
float imviewer::m_zoomLevel {1} protected
Definition at line 344 of file imviewer.hpp.
Referenced by imviewerForm::change_center(), imviewerForm::post_zoomLevel(), and zoomLevel().
m_zoomLevelMax
float imviewer::m_zoomLevelMax {64} protected
Definition at line 346 of file imviewer.hpp.
Referenced by zoomLevel(), and zoomLevelMax().
m_zoomLevelMin
float imviewer::m_zoomLevelMin {0.125} protected
Definition at line 345 of file imviewer.hpp.
Referenced by zoomLevel(), and zoomLevelMin().
RealTimeEnabled
bool imviewer::RealTimeEnabled {true} protected
Controls whether imviewer is using real-time data.
Definition at line 389 of file imviewer.hpp.
Referenced by set_RealTimeEnabled().
RealTimeStopped
bool imviewer::RealTimeStopped {false} protected
Set when user temporarily freezes real-time data viewing.
Definition at line 390 of file imviewer.hpp.
Referenced by imviewerForm::freezeRealTime(), and set_RealTimeStopped().
sat_level
float imviewer::sat_level {1e30} protected
Definition at line 329 of file imviewer.hpp.
Referenced by changeImdata().
saturated
int imviewer::saturated {0} protected
Definition at line 330 of file imviewer.hpp.
Referenced by changeImdata(), and imviewerForm::postChangeImdata().
sigsegvFd
int imviewer::sigsegvFd static private
Definition at line 409 of file imviewer.hpp.
Referenced by handleSigSegv(), imviewer(), and st_handleSigSegv().
snSegv
QSocketNotifier* imviewer::snSegv private
Definition at line 411 of file imviewer.hpp.
Referenced by handleSigSegv(), and imviewer().
userBox_i0
int64_t imviewer::userBox_i0 protected
Definition at line 366 of file imviewer.hpp.
Referenced by changeImdata(), imviewerForm::imviewerForm(), imviewerForm::postSetImsize(), setUserBoxActive(), and imviewerForm::userBoxMoved().
userBox_i1
int64_t imviewer::userBox_i1 protected
Definition at line 367 of file imviewer.hpp.
Referenced by imviewerForm::imviewerForm(), imviewerForm::postSetImsize(), setUserBoxActive(), and imviewerForm::userBoxMoved().
userBox_j0
int64_t imviewer::userBox_j0 protected
Definition at line 368 of file imviewer.hpp.
Referenced by changeImdata(), imviewerForm::imviewerForm(), imviewerForm::postSetImsize(), setUserBoxActive(), and imviewerForm::userBoxMoved().
userBox_j1
int64_t imviewer::userBox_j1 protected
Definition at line 369 of file imviewer.hpp.
Referenced by changeImdata(), imviewerForm::imviewerForm(), imviewerForm::postSetImsize(), setUserBoxActive(), and imviewerForm::userBoxMoved().
userBox_max
float imviewer::userBox_max protected
Definition at line 376 of file imviewer.hpp.
Referenced by changeImdata(), imviewerForm::reStretch(), and setUserBoxActive().
userBox_min
float imviewer::userBox_min protected
Definition at line 377 of file imviewer.hpp.
Referenced by changeImdata(), imviewerForm::reStretch(), and setUserBoxActive().
userBoxActive
int imviewer::userBoxActive {0} protected
Definition at line 363 of file imviewer.hpp.
Referenced by changeImdata(), getUserBoxActive(), setUserBoxActive(), and imviewerForm::toggleUserBox().
warning_color
QColor imviewer::warning_color protected
Definition at line 208 of file imviewer.hpp.
Referenced by load_colorbar().
The documentation for this class was generated from the following files:
/home/jrmales/Source/c/rtimv/src/imviewer.hpp
/home/jrmales/Source/c/rtimv/src/imviewer.cpp