rtimv: /home/jrmales/Source/c/rtimv/src/colorMaps.hpp File Reference
colorMaps.hpp File Reference
Functions
int load_colorbar_jet (QImage *qim)
Jet: load the Matlab Jet colormap.
int load_colorbar_hot (QImage *qim)
Hot: load the Matlab Hot colormap.
int load_colorbar_bone (QImage *qim)
Bone: load the Matlab Bone colormap.
Function Documentation
load_colorbar_bone()
int load_colorbar_bone (QImage * qim) inline
Bone: load the Matlab Bone colormap.
Definition at line 426 of file colorMaps.hpp.
Referenced by imviewer::load_colorbar().
load_colorbar_hot()
int load_colorbar_hot (QImage * qim) inline
Hot: load the Matlab Hot colormap.
Definition at line 348 of file colorMaps.hpp.
Referenced by imviewer::load_colorbar().
load_colorbar_jet()
int load_colorbar_jet (QImage * qim) inline
Jet: load the Matlab Jet colormap.
Definition at line 7 of file colorMaps.hpp.
Referenced by imviewer::load_colorbar().